import { ArrowRightLeft, Crosshair, HeartPulse, LogOut, MapPin, WalletCards } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import DigitalDonorCard from '@/components/DigitalDonorCard';
import BloodUnitTimeline from '@/components/BloodUnitTimeline';
import KavachAI from '@/components/KavachAI';
import { useAuth } from '@/context/auth';
import { supabase } from '@/context/supabase';
import type { Donor, InventoryUnit } from '@/types/database';

export default function DonorDashboard(): JSX.Element | null {
  const { user, logout } = useAuth(); const [, navigate] = useLocation(); const [donor, setDonor] = useState<Donor | null>(null); const [units, setUnits] = useState<InventoryUnit[]>([]); const [radius, setRadius] = useState(50); const [recipient, setRecipient] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { let active = true; const load = async (): Promise<void> => { const donorQuery = await supabase.from('donors').select('*').limit(1).maybeSingle(); const inventoryQuery = await supabase.from('blood_inventory').select('*').limit(20); if (active) { setDonor(donorQuery.data); setUnits(inventoryQuery.data ?? []); } }; void load(); return () => { active = false; }; }, []);
  if (!user) { navigate('/'); return null; }
  const name = donor?.full_name ?? user.name;
  return <main className="min-h-screen bg-[#030712] p-4 text-white md:p-8"><header className="mx-auto mb-8 flex max-w-7xl items-center justify-between"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[.25em] text-cyan-300"><HeartPulse className="h-4 w-4" /> Rakt Kavach • Donor Wallet</p><h1 className="mt-2 text-3xl font-black">Welcome back, {name.split(' ')[0]}</h1></div><button type="button" onClick={() => { logout(); navigate('/'); }} className="rounded-xl border border-white/10 p-3 text-slate-300 hover:bg-white/10" aria-label="Sign out"><LogOut className="h-5 w-5" /></button></header><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.1fr_.9fr]"><DigitalDonorCard name={name} bloodGroup={donor?.blood_group ?? 'B+'} credits={1} /><section className="space-y-4"><div className="rounded-3xl border border-rose-300/20 bg-rose-300/[.06] p-5"><div className="flex items-center gap-3"><Crosshair className="h-6 w-6 text-rose-300" /><div><h2 className="font-bold">Emergency blood request</h2><p className="text-sm text-slate-400">Find verified blood support near you.</p></div></div><div className="mt-5 flex items-center gap-3"><MapPin className="h-5 w-5 text-cyan-300" /><input type="range" min="5" max="100" value={radius} onChange={(event) => setRadius(Number(event.target.value))} className="w-full accent-cyan-300" /><span className="text-sm">{radius} km</span></div></div><div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="mb-3 flex items-center gap-2"><ArrowRightLeft className="h-5 w-5 text-cyan-300" /><h2 className="font-bold">Transfer blood credit</h2></div><div className="flex gap-2"><input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="Recipient ID e.g. RC-IN-1234" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-cyan-300" /><button type="button" onClick={() => { if (/^RC-[A-Z0-9-]{4,}$/.test(recipient)) { setMessage('Transfer request queued for secure verification.'); setRecipient(''); } else setMessage('Enter a valid recipient ID.'); }} className="rounded-xl bg-cyan-300 px-4 text-sm font-bold text-slate-950"><WalletCards className="h-4 w-4" /></button></div>{message && <p className="mt-3 text-xs text-cyan-200">{message}</p>}</div><KavachAI /></section></div><div className="mx-auto mt-6 max-w-7xl"><BloodUnitTimeline /><p className="mt-3 text-xs text-slate-500">{units.length} inventory units currently visible through the connected blood network.</p></div></main>;
}
