import { Camera, CheckCircle2, ClipboardList, PackageCheck, ScanLine, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';

import { useAuth } from '@/context/auth';
import { useI18n } from '@/context/i18n';
import { supabase } from '@/context/supabase';
import type { InventoryUnit } from '@/types/database';

export default function HospitalDashboard(): JSX.Element | null {
  const { user, logout } = useAuth(); const [, navigate] = useLocation(); const { t } = useI18n(); const [token, setToken] = useState(''); const [result, setResult] = useState(''); const [inventory, setInventory] = useState<InventoryUnit[]>([]);
  useEffect(() => { let active = true; const load = async (): Promise<void> => { const query = await supabase.from('blood_inventory').select('*').limit(30); if (active) setInventory(query.data ?? []); }; void load(); return () => { active = false; }; }, []);
  const scan = (): void => { if (!token.trim()) { setResult('Present a donor or unit QR identifier.'); return; } setResult('Eligibility check queued: identity and safety screening required before donation.'); };
  if (!user) { navigate('/'); return null; }
  return <main className="min-h-screen bg-[#030712] p-4 text-white md:p-8"><header className="mx-auto mb-8 flex max-w-7xl items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-300">{t('hospital')}</p><h1 className="text-2xl font-bold">Rakt Kavach clinical scanner</h1></div><button onClick={() => { logout(); navigate('/'); }} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{t('logout')}</button></header><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl border border-cyan-400/20 bg-slate-950/70 p-6"><div className="mb-6 flex items-center gap-3"><ScanLine className="text-cyan-300" /><div><p className="text-xs uppercase tracking-widest text-cyan-300">{t('scanner')}</p><h2 className="text-xl font-bold">Eligibility scanner</h2></div></div><div className="grid place-items-center rounded-xl border border-dashed border-white/15 bg-white/[.03] py-10"><Camera size={40} className="text-slate-500" /><p className="mt-3 text-xs text-slate-400">Camera scanner ready</p></div><input value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste QR token / RC identifier" className="mt-4 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm" /><button onClick={scan} className="mt-3 w-full rounded-xl bg-[#ff0033] px-4 py-3 text-sm font-semibold">Run safety screening</button>{result && <p className="mt-4 rounded-lg bg-cyan-400/10 p-3 text-xs text-cyan-100">{result}</p>}</section><section className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[['0','Lifetime donations',ClipboardList],['0','Safety flags',ShieldAlert],['0','Eligible today',CheckCircle2]].map(([value,label,Icon]) => <div key={String(label)} className="rounded-xl border border-white/10 bg-white/[.04] p-4"><Icon className="text-cyan-300" size={18} /><p className="mt-3 text-2xl font-black">{String(value)}</p><p className="text-xs text-slate-400">{String(label)}</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center gap-2"><PackageCheck className="text-emerald-400" /><h2 className="font-bold">Live local inventory</h2></div><div className="mt-4 space-y-2">{inventory.length ? inventory.map((unit) => <div key={unit.id} className="flex items-center justify-between rounded-lg bg-white/[.04] px-3 py-3 text-sm"><span>{unit.facility_name} · {unit.blood_group}</span><span className="font-mono text-emerald-300">{unit.units} units</span></div>) : <p className="py-6 text-center text-sm text-slate-500">No inventory records returned.</p>}</div></div><div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-xs text-amber-100">Safety filters include HIV screening, medication review, thalassemia risk, recent donation interval, and clinician approval.</div></section></div></main>;
}
