import { FormEvent, useRef, useState } from 'react';
import { useLocation } from 'wouter';
import { useAuth } from '@/context/auth';

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export default function ProfileCompletion(): JSX.Element {
  const { user, saveDonorProfile } = useAuth(); const [, navigate] = useLocation(); const fileRef = useRef<HTMLInputElement>(null);
  const [form, setForm] = useState({ full_name: user?.name ?? '', blood_group: '', state: '', district: '', block: '', pincode: '', photo_url: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  if (!user || user.role !== 'donor') { navigate('/'); return null; }
  const submit = async (event: FormEvent): Promise<void> => { event.preventDefault(); setError(''); if (!form.full_name.trim() || !form.blood_group || !form.state.trim() || !form.district.trim() || !form.block.trim() || !/^\d{6}$/.test(form.pincode) || !form.photo_url) { setError('Complete every field and add a profile photo.'); return; } setSaving(true); try { await saveDonorProfile(form); navigate('/donor'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save profile'); } finally { setSaving(false); } };
  const photo = (file: File): void => { const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, photo_url: String(reader.result) })); reader.readAsDataURL(file); };
  return <main className="min-h-screen bg-[#030712] p-4 text-white md:p-8"><form onSubmit={submit} className="mx-auto max-w-2xl rounded-3xl border border-cyan-300/20 bg-white/[.05] p-6"><h1 className="text-3xl font-black">Complete donor profile</h1><p className="mt-2 text-sm text-slate-400">Profile completion is required before accessing your donor wallet.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Profile photo<input ref={fileRef} type="file" accept="image/*" capture="user" onChange={(e) => e.target.files?.[0] && photo(e.target.files[0])} className="mt-2 block w-full text-sm" required />{form.photo_url && <img src={form.photo_url} alt="Profile preview" className="mt-3 h-20 w-20 rounded-xl object-cover" />}</label><label>Full name<input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} className="mt-2 w-full rounded-xl bg-black/20 px-3 py-3" /></label><label>Verified blood group<select required value={form.blood_group} onChange={(e) => setForm({ ...form, blood_group: e.target.value })} className="mt-2 w-full rounded-xl bg-[#081426] px-3 py-3"> <option value="">Select</option>{BLOOD_GROUPS.map((group) => <option key={group}>{group}</option>)}</select></label>{(['state', 'district', 'block'] as const).map((field) => <label key={field} className="capitalize">{field}<input required value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} className="mt-2 w-full rounded-xl bg-black/20 px-3 py-3" /></label>)}<label>Pincode<input required inputMode="numeric" maxLength={6} value={form.pincode} onChange={(e) => setForm({ ...form, pincode: e.target.value.replace(/\D/g, '').slice(0, 6) })} className="mt-2 w-full rounded-xl bg-black/20 px-3 py-3" /></label></div>{error && <p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}<button disabled={saving} className="mt-6 w-full rounded-xl bg-cyan-300 py-3 font-bold text-slate-950">{saving ? 'Saving…' : 'Save profile'}</button></form></main>;
}
