import { Activity, Droplets, Map, Radio, TrendingUp } from 'lucide-react';

export type CommandScope = 'who_command' | 'national_board' | 'state_command' | 'district_authority' | 'block_officer' | 'system_admin';

const inventory = [['O+', 68], ['B+', 54], ['A+', 42], ['AB+', 24], ['O-', 18], ['B-', 12]];
const nodes = [['Delhi NCR', 'Optimal', 'text-emerald-300'], ['Mumbai', 'Watch', 'text-amber-300'], ['Bengaluru', 'Optimal', 'text-emerald-300'], ['Kolkata', 'Syncing', 'text-cyan-300'], ['Guwahati', 'Critical', 'text-rose-300']];

export default function NationalGrid({ scope }: { scope: CommandScope }): JSX.Element {
  const canBroadcast = scope !== 'system_admin';
  const title = scope === 'who_command' ? 'WHO Command Center' : scope === 'state_command' ? 'State Command Center' : scope === 'national_board' ? 'National Blood Grid' : 'Regional Command Dashboard';
  return <div className="space-y-5">
    <div className="grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <section className="rounded-3xl border border-cyan-300/20 bg-[#071426] p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-300">Live network topology</p><h2 className="text-xl font-bold">{title}</h2></div><Map className="h-6 w-6 text-cyan-300" /></div><div className="relative flex min-h-72 items-center justify-center overflow-hidden rounded-2xl border border-white/10 bg-[#0b1e35] bg-[radial-gradient(circle,rgba(34,211,238,.18)_1px,transparent_1px)] [background-size:24px_24px]"><div className="absolute h-52 w-40 rounded-[45%] border-2 border-cyan-300/50 shadow-[0_0_50px_rgba(34,211,238,.15)]" /><div className="absolute left-[39%] top-[28%] h-3 w-3 rounded-full bg-emerald-300 shadow-[0_0_18px_#6ee7b7]" /><div className="absolute left-[56%] top-[48%] h-3 w-3 rounded-full bg-amber-300 shadow-[0_0_18px_#fcd34d]" /><div className="absolute left-[48%] top-[68%] h-3 w-3 rounded-full bg-cyan-300 shadow-[0_0_18px_#67e8f9]" /><span className="absolute bottom-3 left-3 flex items-center gap-2 text-xs text-emerald-300"><Radio className="h-3 w-3 animate-pulse" /> LIVE • 128 regional nodes</span></div></section>
      <section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold">Live blood inventory</h2><Droplets className="h-5 w-5 text-rose-300" /></div>{inventory.map(([group, value]) => <div key={group} className="mb-4"><div className="mb-1 flex justify-between text-sm"><span>{group}</span><span className="text-slate-400">{value}% capacity</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-rose-400 to-cyan-300" style={{ width: `${value}%` }} /></div></div>)}</section>
    </div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="mb-5 flex items-center gap-2 font-bold"><TrendingUp className="h-5 w-5 text-cyan-300" /> Demand vs supply</h2><div className="flex h-44 items-end gap-3 border-b border-white/10 px-2">{[45, 70, 52, 84, 62, 92, 76].map((height, index) => <div key={index} className="flex flex-1 items-end gap-1"><div className="w-1/2 rounded-t bg-rose-400/80" style={{ height: `${height}%` }} /><div className="w-1/2 rounded-t bg-cyan-300/80" style={{ height: `${Math.max(20, height - 18)}%` }} /></div>)}</div><div className="mt-3 flex justify-center gap-5 text-xs text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-rose-400" />Demand</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-cyan-300" />Supply</span></div></section><section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><Activity className="h-5 w-5 text-emerald-300" /> Regional node status</h2>{nodes.map(([node, status, color]) => <div key={node} className="flex items-center justify-between border-b border-white/10 py-3 last:border-0"><span>{node}</span><span className={`text-xs font-semibold ${color}`}>{status}</span></div>)}</section></div>
    {!canBroadcast && <p className="rounded-xl border border-slate-500/30 bg-slate-500/10 p-3 text-sm text-slate-300">SOS broadcast is disabled for Super Admin. Operational broadcasts are restricted to WHO and National/State Command Centers.</p>}
  </div>;
}
